# Generated by Django 4.2 on 2023-04-03 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('in_progress', 'In Progress'), ('canceled', 'Canceled'), ('ready', 'Ready')], default='in_progress', max_length=20)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrappedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url_name', models.CharField(blank=True, max_length=150)),
                ('link', models.URLField()),
                ('webpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='link_web_scrapper.webpage')),
            ],
        ),
    ]
